import { Provider } from "@/components/ui/provider"
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}) {
    return (
        <html suppressHydrationWarning>
            <body>
                <Provider>{children}</Provider>
            </body>
        </html>)
}
